### ISSUE TITLE
Webview2Loader.dll not detected

### ISSUE THREAD

**Issue by leaanthony** [jchv/go-webview2#26]
Hey there 😄 Looks like webviewloader cannot detect `WebView2Loader.dll` in every scenario except if it is alongside the binary. Is that because the official DLL isn't in a default library directory? Cheers.

**Comment by jchv** [comment]
In which directory are you trying to have it pick up WebView2Loader.dll from? In theory we should be getting the [Standard Search Order for Desktop Applications](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications).

**Comment by leaanthony** [comment]
Yeah, I assumed that if you use `NewLazyDLL("WebView2Loader.dll")` it would search those paths and also assumed that "WebView2Loader.dll" would be installed in one of those paths. I mean, it's a lot of assumptions granted 😂

**Comment by jchv** [comment]
Yeah, Webview2Loader won't be installed in a system directory, to my understanding; it's part of the Webview2 SDK, not the runtime. You need to have it bundled with your app. That's the main reason why go-webview2 bundles it and uses go-winloader.

Webview2Loader doesn't have a whole lot of functionality in it, though. It mainly exists to just provide the logic for finding and loading Webview2. I have reverse engineered it over here: [OpenWebView2Loader](https://github.com/jchv/OpenWebView2Loader).

**Comment by leaanthony** [comment]
I think porting that to Go would be fun!
