### ISSUE TITLE
webview failing to start

### ISSUE THREAD

**Issue by princessmortix** [jchv/go-webview2#34]
~~While testing the demo, i am getting this error:~~

```
2022/02/10 17:34:15 Result: 80070002
2022/02/10 17:34:15 Failed to load webview.
```

~~What I could be doing wrong? I'm using Go 1.17.6, Windows 10 21H1 and have downloaded and installed WebView2 runtime.~~

Nevermind, seems like i had to download "Evergreen Bootstrapper" too

**Comment by jchv** [comment]
Interesting. I was unaware that this was required, and this may signal a documentation issue.
