### ISSUE TITLE
Compared to astilectron,which is better

### ISSUE THREAD

**Issue by passerbyo** [jchv/go-webview2#47]

**Comment by jchv** [comment]
Sorry I never answered this.

Astilectron is a very different project of which I am not very familiar with. Astilectron is cross-platform and oriented around app development, whereas go-webview2 is Windows-only and oriented around providing Go bindings to the Windows webview2 component. Instead, it would make sense to compare Astilectron to Wails, but I don't have the answer as for which is ultimately better. Wails will have less moving parts, but is quite different of an approach.
