### ISSUE TITLE
How to solve the cross domain problem of js?

### ISSUE THREAD

**Issue by ajuner** [jchv/go-webview2#58]
Access to script at 'file:///D:/goproject/src/test-webview/app/assets/client.80aeb8cb.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome-untrusted, https, edge.

**Comment by ajuner** [comment]
local html

**Comment by ajuner** [comment]
I found a way to solve it, but I encountered a new problem. I want to pass the parameter to ”CreateCoreWebView2EnvironmentWithOptions“, but this seems incorrect
![image](https://user-images.githubusercontent.com/53512912/194998487-f8d6f91a-ebdf-49b4-bf20-d345d0996311.png)

**Comment by gizmo-ds** [comment]
You can try to use [SetVirtualHostNameToFolderMapping](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.1462.37), a simple [example](https://github.com/gizmo-ds/go-webview2-example/blob/7c63ec1c9ec5de9de12ccd5ac0cbf87c12d9e66f/main.go#L39)

**Comment by CarsonSlovoka** [comment]
I don't know how to add `ICoreWebView2EnvironmentOptions` for `CreateCoreWebView2EnvironmentWithOptions`, always get crush

[ICoreWebView2EnvironmentOptionsVTbl](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/win32/webview2/ns-webview2-ICoreWebView2EnvironmentOptionsvtbl)
```go
type ICoreWebView2EnvironmentOptions struct {
		queryInterface                            uintptr
		addRef                                    uintptr
		release                                   uintptr
		getAdditionalBrowserArguments             uintptr
		putAdditionalBrowserArguments             uintptr
		getLanguage                               uintptr
		putLanguage                               uintptr
		getTargetCompatibleBrowserVersion         uintptr
		putTargetCompatibleBrowserVersion         uintptr
		getAllowSingleSignOnUsingOSPrimaryAccount uintptr
		putAllowSingleSignOnUsingOSPrimaryAccount uintptr
	}
```
