### ISSUE TITLE
How to get the newer version of WebView2Loader.dll

### ISSUE THREAD

**Issue by 758F08FE920B1765** [jchv/go-webview2#59]
thanks @jchv

**Comment by jchv** [comment]
The NuGet WebView2 package contains the latest WebView2Loader.dll.

1. Download NuGet package file from https://www.nuget.org/packages/Microsoft.Web.WebView2/

2. Either rename file extension from .nupkg to .zip or open using 7-Zip using Open With.

3. Go to "runtimes" folder, then pick a folder depending on which architecture you want, and under that go to the "native" folder. There should be a file named WebView2Loader.dll.
