### ISSUE TITLE
[Feature Request] Customize title bar icon

### ISSUE THREAD

**Issue by Tim-Paik** [jchv/go-webview2#6]
Is there a way to customize the title bar icon?
I only have one way to remove the title icon (But based on a version of my fork a long time ago)
[link](https://github.com/Tim-Paik/webview2/commit/b64c376ac28544e1d5489a7fe5b94f9146e4650f)

**Comment by leaanthony** [comment]
How do you propose it would work? You'd normally need to use `winres` or similar asset compiler to add in the data to the binary. I've done this by using webview2 as a component and treating it as an external concern.

**Comment by jchv** [comment]
I think it should be possible to use `user32:CreateIcon` to get an `HICON` handle for an image in-memory, then set it to the `hIcon` member of the `WNDCLASSEX` structure that is registered in Create.

Not sure what the API for this might look like, though.

**Comment by jchv** [comment]
I believe this was fixed in #43, and can be done using `NewWithOptions`. You do need to embed the icon into your binary, though.
