### ISSUE TITLE
w.Bind() and w.Init() not working on first page load

### ISSUE THREAD

**Issue by rcambrj** [jchv/go-webview2#71]
On Windows, it seems that `w.Bind()` and `w.Init()` don't work on the first page load.

A workaround is to reload the page.

I've reproduced the problem along with a workaround: https://github.com/rcambrj/webview2-bug

**Comment by herrmarten** [comment]
execute bind after you used navigate.
```go
	w.Bind("goFunctionName", func() {
		log.Println("Received message")
	})

	w.Navigate("http://127.0.0.1:8443")
	
	w.Eval(`
	
	document.addEventListener("DOMContentLoaded", function() {
		alert('DOMContentLoaded event triggered');
		if (window.chrome && window.chrome.webview) {
			window.goFunctionName();
		}
		alert('DOMContentLoaded event fully processed');
	});
`)
```

works for me

**Comment by rcambrj** [comment]
@herrmarten it seems that I'd forgotten to mention that this is a Windows only problem. I've updated the description to reflect that. The repro steps in the linked repository were solid when I raised the issue, did you try those steps (on Windows)?

**Comment by herrmarten** [comment]
I had the same behavior as you mentioned, until I flipped order. I am cross
building in a dockercontainer (Ubuntu) inside my WSL. Build target is also
windows.

Robert Cambridge ***@***.***> schrieb am So., 18. Aug. 2024,
09:46:

**Comment by rcambrj** [comment]
Thanks for confirming and for taking the time to investigate 🙂
